-- MOVA content candidate: 121 new phrases (NEW_PHRASES sheet).
-- Not production-approved: 107 enter native_review, 14 safety-sensitive enter
-- safety_review — the same convention the existing 28 safety phrases follow,
-- so none of them is readable through RLS until a reviewer approves it.
with src (external_id, german, russian, prof_slug, category, intent, priority,
          stage, freq, difficulty, safety, source_ref, confidence, notes) as (values
  ('N-CORE-001','Nimm das.','Возьми это.',null,'Basic verbs','trade_task','A','WORKING_CORE',80,1,false,'existing verified pattern (holen/bringen structure)','HIGH','nehmen: 0 существующих команд'),
  ('N-CORE-002','Nimm das mal kurz.','Возьми это на минутку.',null,'Basic verbs','trade_task','B','WORKING_CORE',50,1,false,'analogy to existing "Hol mal kurz die Wasserwaage rüber"','MEDIUM','nehmen: разговорный вариант с mal kurz'),
  ('N-CORE-003','Nimm das mit.','Возьми это с собой.',null,'Basic verbs','trade_task','A','WORKING_CORE',80,1,false,'general German, standard separable verb','HIGH','nehmen + mit: типовая конструкция "взять с собой"'),
  ('N-CORE-004','Nimm zwei Stück mit.','Возьми с собой две штуки.',null,'Basic verbs','trade_task','B','WORKING_CORE',50,1,false,'general German','HIGH','nehmen + количество'),
  ('N-CORE-005','Gib mir das.','Дай мне это.',null,'Basic verbs','trade_task','A','WORKING_CORE',80,1,false,'general German, standard imperative','HIGH','geben: 0 существующих команд'),
  ('N-CORE-006','Gib mir mal den Hammer.','Дай мне молоток.',null,'Basic verbs','trade_task','A','WORKING_CORE',80,1,false,'general German + existing tool vocabulary (Hammer, C082)','HIGH','geben + конкретный инструмент'),
  ('N-CORE-007','Gib das weiter.','Передай это дальше.',null,'Basic verbs','trade_task','B','WORKING_CORE',50,1,false,'general German, separable verb weitergeben','MEDIUM','geben: передача по цепочке (частая ситуация на объекте)'),
  ('N-CORE-008','Trag das nach oben.','Отнеси это наверх.',null,'Basic verbs','trade_task','A','WORKING_CORE',80,1,false,'general German + existing direction vocabulary','HIGH','tragen в значении "нести": 0 существующих (P0329 — только "нанеси раствор")'),
  ('N-CORE-009','Trag das zu zweit.','Несите это вдвоём.',null,'Basic verbs','trade_task','B','WORKING_CORE',50,1,false,'general German','MEDIUM','tragen: тяжёлый груз — обычная рабочая ситуация'),
  ('N-CORE-010','Halt das mal.','Подержи это.',null,'Basic verbs','trade_task','A','WORKING_CORE',80,1,false,'general German, standard imperative','HIGH','halten в значении "держи это": 0 существующих (P0190 — только safety "держи дистанцию")'),
  ('N-CORE-011','Halt das fest.','Держи это крепко.',null,'Basic verbs','trade_task','A','WORKING_CORE',80,1,false,'general German','HIGH','halten + fest — частый паттерн "держи крепко"'),
  ('N-CORE-012','Halt das gerade.','Держи это ровно.',null,'Basic verbs','trade_task','B','WORKING_CORE',50,1,false,'general German','MEDIUM','halten + оценка положения'),
  ('N-CORE-013','Das ist im ersten Stock.','Это на первом этаже.',null,'Location: building','trade_task','A','WORKING_CORE',80,1,false,'existing verified pattern (Lingolia Bau vocabulary confirms Stockwerk)','HIGH','Stockwerk: 0 существующих'),
  ('N-CORE-014','Geh ins Erdgeschoss.','Иди на первый этаж (уровень земли).',null,'Location: building','trade_task','A','WORKING_CORE',80,1,false,'general German building terminology','HIGH','Erdgeschoss — стандартное немецкое обозначение первого этажа'),
  ('N-CORE-015','Das Material ist im Keller.','Материал в подвале.',null,'Location: building','trade_task','A','WORKING_CORE',80,1,false,'general German','HIGH','Keller: 0 существующих'),
  ('N-CORE-016','Geh in den zweiten Raum links.','Иди во вторую комнату слева.',null,'Location: building','trade_task','B','WORKING_CORE',50,1,false,'general German','MEDIUM','Raum + порядковое число + направление'),
  ('N-CORE-017','Nimm die Treppe nach oben.','Поднимись по лестнице.',null,'Location: building','trade_task','A','WORKING_CORE',80,1,false,'general German','HIGH','Treppe: 0 существующих'),
  ('N-CORE-018','Der Eingang ist auf der anderen Seite.','Вход с другой стороны.',null,'Location: building','trade_task','B','WORKING_CORE',50,1,false,'general German','MEDIUM','Eingang/Ausgang: 0 существующих'),
  ('N-CORE-019','Warte draußen.','Подожди снаружи.',null,'Location: building','trade_task','A','WORKING_CORE',80,1,false,'general German','HIGH','draußen/drinnen: 0 существующих'),
  ('N-CORE-020','Das Werkzeug bleibt drinnen.','Инструмент остаётся внутри.',null,'Location: building','trade_task','B','WORKING_CORE',50,1,false,'general German','MEDIUM','drinnen'),
  ('N-CORE-021','Kannst du das abnehmen?','Можешь принять работу?',null,'Handover','trade_task','B','WORKING_CORE',50,1,false,'construction handover terminology (Bauabnahme)','MEDIUM','Формальная сдача: 0 существующих'),
  ('N-CORE-022','Ich übergebe dir das jetzt.','Я передаю тебе это сейчас.',null,'Handover','trade_task','C','WORKING_CORE',25,1,false,'general German','MEDIUM','übergeben — формальная передача участка работы'),
  ('N-CORE-023','Die Abnahme ist morgen.','Приёмка работы завтра.',null,'Handover','trade_task','B','WORKING_CORE',50,1,false,'general German construction terminology','MEDIUM','Abnahme — стандартный строительный термин'),
  ('N-CORE-024','Ist das abgenommen?','Это принято (проверено и одобрено)?',null,'Handover','trade_task','C','WORKING_CORE',25,1,false,'general German','MEDIUM','abgenommen — статус приёмки'),
  ('N-CORE-025','Woher kommen Sie?','Откуда вы?',null,'Sie recognition','trade_task','B','WORKING_CORE',50,1,false,'general German, standard formal question','HIGH','Формальный вопрос при первом знакомстве'),
  ('N-CORE-026','Haben Sie schon Erfahrung damit?','У вас уже есть опыт в этом?',null,'Sie recognition','trade_task','C','WORKING_CORE',25,1,false,'general German','MEDIUM','Формальный вопрос об опыте при знакомстве'),
  ('N-CORE-027','Erst miss es, dann schneid es zu.','Сначала измерь, потом отрежь.',null,'Natural speech','trade_task','B','WORKING_CORE',50,2,false,'existing verified pattern P0109 "Zuerst messen, dann schneiden"','HIGH','Составная команда: 0 существующих кроме одной'),
  ('N-CORE-028','Mach das fertig und räum danach auf.','Закончи это и потом убери.',null,'Natural speech','trade_task','B','WORKING_CORE',50,2,false,'general German','MEDIUM','Составная команда с "und...danach"'),
  ('N-CORE-029','Hol das Werkzeug und fang gleich an.','Принеси инструмент и сразу начинай.',null,'Natural speech','trade_task','B','WORKING_CORE',50,2,false,'existing verified pattern (holen + separate command)','MEDIUM','Составная команда, естественный темп речи бригадира'),
  ('N-TB-001','Miss die Höhe vom Boden bis zur Decke.','Замерь высоту от пола до потолка.','trockenbau','Layout','trade_task','A','TRADE',80,1,false,'existing verified pattern + measuring vocabulary','HIGH','Разметка в самом начале: 0 существующих'),
  ('N-TB-002','Zeichne die Wandlinie mit dem Laser an.','Отметь линию стены лазером.','trockenbau','Layout','trade_task','B','TRADE',50,1,false,'trade source: baywa-baustoffe.de Trockenbauwand-Anleitung','MEDIUM','Kreuzlinien-Laser используется для разметки'),
  ('N-TB-003','Miss den Abstand zwischen den Ständern.','Замерь расстояние между стойками.','trockenbau','Layout','trade_task','A','TRADE',80,1,false,'trade source: MioTools Trockenbauprofile','HIGH','Расстояние между CW-профилями — регулярная проверка'),
  ('N-TB-004','Schneid das Profil mit der Blechschere.','Отрежь профиль ножницами по металлу.','trockenbau','Tools','trade_task','A','TRADE',80,1,false,'trade source: baywa-baustoffe.de','HIGH','Инструмент по имени в команде: 0 существующих'),
  ('N-TB-005','Verbind die Profile mit der Crimperzange.','Соедини профили обжимными клещами.','trockenbau','Tools','trade_task','B','TRADE',50,1,false,'trade source: openhouse-site.de','MEDIUM','Crimperzange — специфический инструмент соединения профилей'),
  ('N-TB-006','Schraub das mit dem Schnellbauschrauber.','Прикрути это шуруповёртом для гипсокартона.','trockenbau','Tools','trade_task','A','TRADE',80,1,false,'trade source: baywa-baustoffe.de','HIGH','Schnellbauschrauber по имени в команде'),
  ('N-TB-007','Häng hier einen Direktabhänger ein.','Повесь здесь прямой подвес.','trockenbau','Ceiling','trade_task','B','TRADE',50,1,false,'trade source: MioTools','MEDIUM','Direktabhänger — упомянут в задании, не покрыт'),
  ('N-TB-008','Lass hier eine Aussparung für das Kabel.','Оставь здесь отверстие под кабель.','trockenbau','Coordination','trade_task','A','TRADE',80,1,false,'derived from real workflow','HIGH','Межпрофессиональная координация: 0 существующих'),
  ('N-TB-009','Warte, der Elektriker ist noch nicht fertig.','Подожди, электрик ещё не закончил.','trockenbau','Coordination','trade_task','B','TRADE',50,1,false,'derived from real workflow','MEDIUM','Координация — реальная точка задержки на объекте'),
  ('N-TB-010','Frag den Elektriker, wo die Dose hinkommt.','Спроси электрика, где будет розетка.','trockenbau','Coordination','trade_task','B','TRADE',50,1,false,'derived from real workflow','MEDIUM','Координация перед зашивкой стены'),
  ('N-TB-011','Erst die Leitungen, dann beplanken.','Сначала проводка, потом обшивка.','trockenbau','Coordination','trade_task','B','TRADE',50,1,false,'existing verified pattern','HIGH','Составная координационная команда'),
  ('N-TB-012','Häng die Platte hier ein und schraub sie fest.','Навесь лист здесь и прикрути.','trockenbau','Natural speech','trade_task','B','TRADE',50,2,false,'general German','MEDIUM','Составная монтажная команда'),
  ('N-FL-001','Hol den Fliesenschneider.','Принеси плиткорез.','fliesenleger','Tools','trade_task','A','TRADE',80,1,false,'existing verified pattern (holen + tool)','HIGH','Инструмент по имени в команде: 0 существующих'),
  ('N-FL-002','Schneid das mit dem Winkelschleifer.','Отрежь это болгаркой.','fliesenleger','Tools','trade_task','B','TRADE',50,1,false,'trade source: OBI Fliesenlegerwerkzeuge','HIGH','Winkelschleifer для сложных резов'),
  ('N-FL-003','Nimm den Zahnspachtel für den Kleber.','Возьми зубчатый шпатель для клея.','fliesenleger','Tools','trade_task','A','TRADE',80,1,false,'trade source: OBI','HIGH','Zahnspachtel по имени в команде'),
  ('N-FL-004','Zeichne die Mittelachse an.','Отметь центральную ось.','fliesenleger','Layout','trade_task','B','TRADE',50,1,false,'trade source: fliesenleger-ratgeber.de','MEDIUM','Разметка раскладки перед укладкой'),
  ('N-FL-005','Plan das Verlegemuster, bevor du anfängst.','Спланируй раскладку перед началом.','fliesenleger','Layout','trade_task','B','TRADE',50,1,false,'trade source: fliesenleger-ratgeber.de','MEDIUM','Планирование раскладки'),
  ('N-MA-001','Miss die Wand für die Tapete aus.','Замерь стену под обои.','maler','Tapezieren','trade_task','A','TRADE',80,1,false,'trade source: ausbildungskompass.de Maler und Lackierer','HIGH','Tapezieren — целая ветвь профессии отсутствовала полностью'),
  ('N-MA-002','Schneid die Tapete auf Länge zu.','Отрежь обои по длине.','maler','Tapezieren','trade_task','A','TRADE',80,1,false,'general German + trade source','HIGH','Раскрой обоев'),
  ('N-MA-003','Rühr den Kleister an.','Разведи обойный клей.','maler','Tapezieren','trade_task','A','TRADE',80,1,false,'general German wallpapering terminology','HIGH','Kleister — специфический клей для обоев'),
  ('N-MA-004','Streich den Kleister auf die Tapete.','Намажь клей на обои.','maler','Tapezieren','trade_task','A','TRADE',80,1,false,'general German','HIGH','Нанесение клея'),
  ('N-MA-005','Häng die Bahn gerade an.','Навесь полотно ровно.','maler','Tapezieren','trade_task','A','TRADE',80,1,false,'general German wallpapering terminology','HIGH','Bahn — стандартный термин «полотно обоев»'),
  ('N-MA-006','Streich die Bahn glatt.','Разгладь полотно.','maler','Tapezieren','trade_task','A','TRADE',80,1,false,'general German','HIGH','Разглаживание после наклейки'),
  ('N-MA-007','Der Stoß muss genau passen.','Стык должен точно совпадать.','maler','Tapezieren','trade_task','B','TRADE',50,1,false,'general German','MEDIUM','Stoß — стык полотен обоев'),
  ('N-MA-008','Schneid den Rand an der Kante ab.','Обрежь край у кромки.','maler','Tapezieren','trade_task','B','TRADE',50,1,false,'general German','MEDIUM','Обрезка лишнего края'),
  ('N-MA-009','Die Tapete löst sich hier.','Обои здесь отклеиваются.','maler','Tapezieren','trade_task','B','TRADE',50,1,false,'general German','MEDIUM','Дефект/переделка обоев'),
  ('N-MA-010','Kleb das nochmal an.','Приклей это заново.','maler','Tapezieren','trade_task','B','TRADE',50,1,false,'existing verified pattern (nochmal)','HIGH','Переделка — существующий паттерн, применён к обоям'),
  ('N-MA-011','Hol eine neue Rolle Tapete.','Принеси новый рулон обоев.','maler','Tapezieren','trade_task','B','TRADE',50,1,false,'existing verified pattern (holen + material)','HIGH','Запрос материала'),
  ('N-MA-012','Wir brauchen noch Kleister.','Нам нужен ещё клей.','maler','Tapezieren','trade_task','B','TRADE',50,1,false,'existing verified pattern (wir brauchen noch)','HIGH','Запрос материала'),
  ('N-MA-013','Spritz das mit dem Spritzgerät.','Нанеси это краскопультом.','maler','Spraying','trade_task','B','TRADE',50,1,false,'trade source: malerbetrieb.de','MEDIUM','Spritzgerät: 0 существующих команд'),
  ('N-MA-014','Halt das Spritzgerät gerade.','Держи краскопульт ровно.','maler','Spraying','trade_task','C','TRADE',25,1,false,'general German','MEDIUM','Техника распыления'),
  ('N-MA-015','Steig auf das Gerüst.','Поднимись на леса.','maler','Height work','trade_task','B','TRADE',50,1,false,'general German','MEDIUM','Работа на высоте для фасадных работ'),
  ('N-MA-016','Sicher die Leiter, bevor du hochsteigst.','Закрепи лестницу, прежде чем подниматься.','maler','Height work','trade_task','B','TRADE',50,1,false,'general German safety pattern','MEDIUM','Безопасность при работе с лестницей'),
  ('N-MA-017','Der Farbton passt nicht genau.','Оттенок не совсем совпадает.','maler','Color','trade_task','C','TRADE',25,1,false,'general German','MEDIUM','Подбор цвета — типичное замечание'),
  ('N-MA-018','Misch die Farbe genau nach der Karte.','Смешай краску точно по образцу.','maler','Color','trade_task','C','TRADE',25,1,false,'general German','MEDIUM','Смешивание по образцу цвета'),
  ('N-MR-001','Stell das Gerüst höher.','Подними леса выше.','maurer','Gerüst','trade_task','A','TRADE',80,1,false,'general German scaffolding terminology','HIGH','Леса — ежедневный инструмент доступа, 0 существующих команд'),
  ('N-MR-002','Sicher das Gerüst, bevor du hochgehst.','Закрепи леса, прежде чем подниматься.','maurer','Gerüst','trade_task','B','TRADE',50,1,false,'general German safety pattern','MEDIUM','Безопасность лесов'),
  ('N-MR-003','Häng die Bohle ein.','Установи доску настила.','maurer','Gerüst','trade_task','B','TRADE',50,1,false,'general German scaffolding terminology','MEDIUM','Bohle — настил лесов'),
  ('N-MR-004','Das Gerüst steht nicht gerade.','Леса стоят не ровно.','maurer','Gerüst','trade_task','B','TRADE',50,1,false,'general German','MEDIUM','Контроль состояния лесов'),
  ('N-MR-005','Zieh das Gerüst ein Stück weiter.','Передвинь леса немного дальше.','maurer','Gerüst','trade_task','B','TRADE',50,1,false,'general German','MEDIUM','Перемещение передвижных лесов'),
  ('N-MR-006','Steig runter, bevor wir das Gerüst bewegen.','Спустись, прежде чем мы будем двигать леса.','maurer','Gerüst','trade_task','B','TRADE',50,1,false,'general German safety pattern','MEDIUM','Безопасность при перемещении лесов'),
  ('N-MR-007','Der Kran bringt die Steine gleich.','Кран сейчас привезёт блоки.','maurer','Logistics','trade_task','B','TRADE',50,1,false,'general German site logistics','MEDIUM','Логистика материала краном'),
  ('N-MR-008','Stapel die Steine hier.','Сложи блоки здесь.','maurer','Logistics','trade_task','B','TRADE',50,1,false,'general German','HIGH','Складирование материала'),
  ('N-MR-009','Die Palette ist noch nicht da.','Поддон ещё не привезли.','maurer','Logistics','trade_task','B','TRADE',50,1,false,'general German + existing vocabulary (Palette confirmed Klett-list)','MEDIUM','Ожидание поставки'),
  ('N-MR-010','Wir haben zu wenig Mörtel bestellt.','Мы заказали слишком мало раствора.','maurer','Logistics','trade_task','C','TRADE',25,1,false,'general German','MEDIUM','Проблема логистики материала'),
  ('N-EL-001','Bohr hier ein Loch für die Dose.','Просверли здесь отверстие под коробку.','elektriker','Tools/Drilling','trade_task','A','TRADE',80,1,false,'trade source: berichtsheftki.de Elektroniker','HIGH','Сверление: 0 существующих команд'),
  ('N-EL-002','Stemm den Kanal für die Leitung.','Пробей штробу под провод.','elektriker','Tools/Drilling','trade_task','A','TRADE',80,1,false,'trade source: berufswelten-energie-wasser.de','HIGH','stemmen — прямая цитата из описания профессии'),
  ('N-EL-003','Schlitz die Wand mit dem Fräser auf.','Прорежь штробу в стене фрезером.','elektriker','Tools/Drilling','trade_task','A','TRADE',80,1,false,'trade source: berufswelten-energie-wasser.de','HIGH','schlitzen — прямая цитата'),
  ('N-EL-004','Nimm den Bohrhammer für die Wand.','Возьми перфоратор для стены.','elektriker','Tools/Drilling','trade_task','A','TRADE',80,1,false,'existing verified vocabulary (Bohrhammer)','HIGH','Bohrhammer по имени в команде'),
  ('N-EL-005','Isolier das Kabelende mit der Abisolierzange ab.','Зачисти конец кабеля стриппером.','elektriker','Tools/Drilling','trade_task','A','TRADE',80,1,false,'trade source: studysmarter.de Elektroinstallation Werkzeug','HIGH','Abisolierzange по имени в команде'),
  ('N-EL-006','Schneid das Kabel mit dem Seitenschneider.','Обрежь кабель бокорезами.','elektriker','Tools/Drilling','trade_task','A','TRADE',80,1,false,'trade source: handwerkszeug.net','HIGH','Seitenschneider по имени в команде'),
  ('N-EL-007','Crimp die Aderendhülse drauf.','Обожми гильзу на жиле.','elektriker','Tools/Drilling','trade_task','B','TRADE',50,1,false,'trade source: studysmarter.de','MEDIUM','Aderendhülsenzange — специфическая операция'),
  ('N-EL-008','Prüf das mit dem Spannungsprüfer.','Проверь индикатором напряжения.','elektriker','Measurement/Testing','trade_task','A','TRADE',80,1,false,'official source: elektrofachkraft.de','HIGH','Измерительный инструмент: 0 существующих команд'),
  ('N-EL-009','Miss die Spannung mit dem Multimeter.','Измерь напряжение мультиметром.','elektriker','Measurement/Testing','trade_task','A','TRADE',80,1,false,'official source: tcs-engineering.de','HIGH','Multimeter по имени в команде'),
  ('N-EL-010','Prüf den Durchgang.','Прозвони цепь.','elektriker','Measurement/Testing','trade_task','B','TRADE',50,1,false,'general German electrical testing terminology','HIGH','Durchgangsprüfung — стандартная проверка'),
  ('N-EL-011','Ist die Leitung spannungsfrei?','Провод обесточен?','elektriker','Measurement/Testing','trade_task','A','TRADE',80,1,false,'official source: elektrofachkraft.de (Spannungsfreiheit feststellen)','HIGH','Ключевой вопрос перед работой с проводкой'),
  ('N-EL-012','Kontrollier den Spannungsprüfer vor der Prüfung.','Проверь индикатор перед использованием.','elektriker','Measurement/Testing','trade_task','B','TRADE',50,1,false,'official source: weka.de','MEDIUM','Проверка прибора перед использованием'),
  ('N-EL-013','Der Test war erfolgreich.','Проверка прошла успешно.','elektriker','Measurement/Testing','trade_task','B','TRADE',50,1,false,'general German','HIGH','Результат проверки'),
  ('N-EL-014','Da ist ein Fehler in der Leitung.','В проводке есть ошибка.','elektriker','Troubleshooting','trade_task','B','TRADE',50,1,false,'general German','HIGH','Поиск неисправности'),
  ('N-EL-015','Such den Fehler von vorne.','Ищи неисправность сначала.','elektriker','Troubleshooting','trade_task','C','TRADE',25,1,false,'general German','MEDIUM','Систематический поиск неисправности'),
  ('N-EL-016','Der grüngelbe Draht ist die Erde.','Жёлто-зелёный провод — это заземление.','elektriker','PE/N/L','trade_task','A','TRADE',80,1,false,'official color-coding standard (DIN VDE — green-yellow = PE)','HIGH','PE (Schutzleiter): 0 существующих'),
  ('N-EL-017','Der blaue Draht ist der Nullleiter.','Синий провод — это ноль.','elektriker','PE/N/L','trade_task','A','TRADE',80,1,false,'official color-coding standard (DIN VDE — blue = N)','HIGH','N (Nullleiter): 0 существующих'),
  ('N-EL-018','Der braune Draht ist die Phase.','Коричневый провод — это фаза.','elektriker','PE/N/L','trade_task','A','TRADE',80,1,false,'official color-coding standard (DIN VDE — brown = L)','HIGH','L (Phase): 0 существующих'),
  ('N-EL-019','Schließ die Erde zuerst an.','Сначала подключи заземление.','elektriker','PE/N/L','trade_task','B','TRADE',50,1,false,'general German electrical practice','MEDIUM','Порядок подключения проводников'),
  ('N-EL-020','Verwechsle Phase und Nullleiter nicht.','Не перепутай фазу и ноль.','elektriker','PE/N/L','trade_task','B','TRADE',50,1,false,'general German','HIGH','Явное предупреждение о частой ошибке'),
  ('N-EL-021','Das ist eine Wechselschaltung.','Это перекрёстная (проходная) схема.','elektriker','Circuits','trade_task','B','TRADE',50,1,false,'trade source: berichtsheftki.de','MEDIUM','Wechselschaltung — распространённая ежедневная задача'),
  ('N-EL-022','Verdraht das nach dem Schaltplan.','Подключи по схеме.','elektriker','Circuits','trade_task','B','TRADE',50,1,false,'trade source: berichtsheftki.de','HIGH','verdrahten по схеме — стандартная задача'),
  ('N-EL-023','Zwei Schalter für ein Licht.','Два выключателя на один свет.','elektriker','Circuits','trade_task','C','TRADE',25,1,false,'derived from Wechselschaltung concept','MEDIUM','Пояснение принципа перекрёстной схемы простыми словами'),
  ('N-EL-024','Ich schalte jetzt frei.','Я сейчас обесточиваю (снимаю напряжение).','elektriker','VDE Safety','safety_recognition','A','TRADE',80,1,true,'official source: VDE 0105-100 / weka.de','HIGH','Freischalten (правило 1 VDE 0105-100): 0 существующих'),
  ('N-EL-025','Warte, bis ich freigeschaltet habe.','Подожди, пока я не обесточу.','elektriker','VDE Safety','safety_recognition','A','TRADE',80,1,true,'official source: VDE 0105-100','HIGH','Ожидание завершения обесточивания'),
  ('N-EL-026','Sicher das gegen Wiedereinschalten.','Заблокируй от повторного включения.','elektriker','VDE Safety','safety_recognition','B','TRADE',50,1,true,'official source: VDE 0105-100','HIGH','Gegen Wiedereinschalten sichern (правило 2)'),
  ('N-EL-027','Rühr das nicht an, bevor ich es geprüft habe.','Не трогай это, пока я не проверил.','elektriker','VDE Safety','safety_recognition','A','TRADE',80,1,true,'official source: VDE 0105-100','HIGH','Запрет действия до проверки Spannungsfreiheit (правило 3)'),
  ('N-EL-028','Es ist spannungsfrei.','Обесточено (напряжения нет).','elektriker','VDE Safety','safety_recognition','A','TRADE',80,1,true,'official source: VDE 0105-100','HIGH','Spannungsfreiheit festgestellt (правило 3)'),
  ('N-EL-029','Vorsicht, das steht noch unter Spannung.','Осторожно, это ещё под напряжением.','elektriker','VDE Safety','safety_recognition','A','TRADE',80,1,true,'official source: general electrical safety + existing pattern P0203','HIGH','Явное предупреждение об опасности'),
  ('N-EL-030','Deck die Nachbarleitung ab, bevor du arbeitest.','Накрой соседний провод, прежде чем начать работу.','elektriker','VDE Safety','safety_recognition','B','TRADE',50,1,true,'official source: VDE 0105-100','MEDIUM','Benachbarte Teile abdecken (правило 5)'),
  ('N-EL-031','Frag die Elektrofachkraft, ob es sicher ist.','Спроси электрика-специалиста, безопасно ли это.','elektriker','VDE Safety','safety_recognition','A','TRADE',80,1,true,'existing verified pattern P0381','HIGH','Прямое указание не действовать самостоятельно'),
  ('N-SHK-001','Nimm die Rohrzange.','Возьми трубный ключ.','sanitaer','Tools','trade_task','A','TRADE',80,1,false,'existing verified vocabulary (Rohrzange)','HIGH','Инструмент по имени: 0 существующих команд'),
  ('N-SHK-002','Press das mit dem Presswerkzeug.','Обожми это пресс-инструментом.','sanitaer','Tools','trade_task','A','TRADE',80,1,false,'trade source: rs-group.de','HIGH','Presswerkzeug по имени в команде'),
  ('N-SHK-003','Löt das mit dem Lötbrenner.','Запаяй это горелкой.','sanitaer','Tools','trade_task','B','TRADE',50,1,false,'trade source: gradmacher.de','HIGH','Lötbrenner по имени в команде'),
  ('N-SHK-004','Schneid das Gewinde mit dem Gewindeschneider.','Нарежь резьбу резьбонарезным инструментом.','sanitaer','Tools','trade_task','B','TRADE',50,1,false,'general German plumbing terminology','MEDIUM','Gewindeschneider по имени в команде'),
  ('N-SHK-005','Nimm den Rohrschneider für das Kupferrohr.','Возьми труборез для медной трубы.','sanitaer','Tools','trade_task','A','TRADE',80,1,false,'general German plumbing terminology','HIGH','Rohrschneider по имени, конкретный материал трубы'),
  ('N-SHK-006','Montier die Toilette.','Установи унитаз.','sanitaer','Fixtures','trade_task','A','TRADE',80,1,false,'general German plumbing terminology','HIGH','Другие сантехприборы кроме раковины: 0 существующих'),
  ('N-SHK-007','Schließ die Dusche an.','Подключи душ.','sanitaer','Fixtures','trade_task','A','TRADE',80,1,false,'general German plumbing terminology','HIGH','Душевая кабина'),
  ('N-SHK-008','Setz die Badewanne ein.','Установи ванну.','sanitaer','Fixtures','trade_task','B','TRADE',50,1,false,'general German plumbing terminology','MEDIUM','Ванна'),
  ('N-SHK-009','Der Abfluss ist verstopft.','Слив забит.','sanitaer','Fixtures','trade_task','B','TRADE',50,1,false,'general German','HIGH','Типичная проблема с прибором'),
  ('N-SHK-010','Prüf, ob die Lüftung frei ist.','Проверь, свободна ли вентиляция.','sanitaer','Fixtures','trade_task','C','TRADE',25,1,false,'general German plumbing/ventilation terminology','MEDIUM','Вентиляция — второстепенный, но реальный элемент'),
  ('N-SHK-011','Ich rieche Gas.','Я чувствую запах газа.','sanitaer','Gas Safety','safety_recognition','A','TRADE',80,1,true,'general German — universal gas-leak recognition phrase','HIGH','Газобезопасность: 0 существующих, критично'),
  ('N-SHK-012','Mach sofort das Fenster auf.','Немедленно открой окно.','sanitaer','Gas Safety','safety_recognition','A','TRADE',80,1,true,'general German emergency response','HIGH','Немедленная реакция на утечку газа'),
  ('N-SHK-013','Schalt kein Licht ein.','Не включай свет.','sanitaer','Gas Safety','safety_recognition','A','TRADE',80,1,true,'general German gas safety','HIGH','Критичный запрет при утечке газа (искра)'),
  ('N-SHK-014','Dreh den Haupthahn zu.','Перекрой главный кран.','sanitaer','Gas Safety','safety_recognition','A','TRADE',80,1,true,'general German emergency shutoff terminology','HIGH','Аварийное отключение'),
  ('N-SHK-015','Ruf sofort den Notdienst.','Немедленно позвони в аварийную службу.','sanitaer','Gas Safety','safety_recognition','A','TRADE',80,1,true,'general German emergency terminology','HIGH','Аварийная служба'),
  ('N-SHK-016','Wir arbeiten hier nicht weiter, bis es sicher ist.','Мы здесь не продолжаем работу, пока не будет безопасно.','sanitaer','Gas Safety','safety_recognition','B','TRADE',50,1,true,'existing verified pattern (P0207 similar structure)','HIGH','Остановка работы до устранения опасности')
), up as (
  insert into phrases (
    external_id, german_text, intent, speaker, profession_id, content_module,
    priority, stage, register_level, frequency_score, difficulty,
    safety_sensitive, safety_approved, verification_status, source_type,
    source_ref, confidence, notes, is_free_preview)
  select s.external_id, s.german, s.intent, 'bauleiter', p.id, s.category,
         s.priority::content_priority, s.stage::content_stage, 2, s.freq, s.difficulty,
         s.safety, false,
         case when s.safety then 'safety_review' else 'native_review' end::verification_status,
         'imported', s.source_ref, s.confidence, s.notes, false
  from src s left join professions p on p.slug = s.prof_slug
  on conflict (external_id) do update set
    german_text         = excluded.german_text,
    intent              = excluded.intent,
    profession_id       = excluded.profession_id,
    content_module      = excluded.content_module,
    priority            = excluded.priority,
    stage               = excluded.stage,
    frequency_score     = excluded.frequency_score,
    difficulty          = excluded.difficulty,
    safety_sensitive    = excluded.safety_sensitive,
    verification_status = excluded.verification_status,
    source_ref          = excluded.source_ref,
    confidence          = excluded.confidence,
    notes               = excluded.notes
  returning id, external_id
)
insert into phrase_translations (phrase_id, language_code, text)
select up.id, 'ru', s.russian from up join src s on s.external_id = up.external_id
on conflict (phrase_id, language_code) do update set text = excluded.text;
